### ISSUE TITLE
[BUG] Shuttle Becomes Stuck when Planetary Encounter Fails to Generate

### ISSUE THREAD

**Issue by MicroMinty** [Whitesands13/Whitesands#784] opened 2021-02-24 00:18 UTC
## Reproduction:

 The issue is the shuttle console breaks and the overmap shown on it breaks as well when you try to land on a strange jungle planet, with the only way to return being having your shuttle called back to where it came.

**Comment by untrius** [comment] 2021-02-24 00:39
Can I get more details on this?  We were able to land on jungle planetoids 2 days ago.  What exactly happened when you tried to land?  Like did the overmap close itself?  And did the console give you a message when it happened?

**Comment by triplezeta** [comment] 2021-02-24 00:48
[BUG]

**Comment by scarwolff** [comment] 2021-02-24 00:56
[BUG]

**Comment by Maldaris** [comment] 2021-02-24 00:56
Figured out the bug:

If the planetary encounter fails to generate, it will prevent the shuttle from docking, and the shuttle becomes basically useless.

**Comment by redguy999** [comment] 2021-04-20 17:02
>even if recalled by the shuttle recall console.

when I first discovered this bug I was able to get the shuttle to dock back at the station, but the console still thought it was in space, trying to dock at the planet.
Also this glitch appears to consistently occur if another location was landed at before landing at the encounter that fails.
So the issue is probably that the game can’t have 2 encounter locations loaded at once.

**Closed** 2021-09-11 22:23 UTC
Labels: Bug
